### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by volcacius** [jafermarq/WinogradAwareNets#7]
Hello,

I'm looking into add support Winograd QAT variants to my quantization library https://github.com/Xilinx/brevitas and I was wondering if you could add a license to the code in this repo? A permissive license like MIT would mean I could use it as a starting point for the implementation. 

Thanks
Alessandro

**Comment by jafermarq** [comment]
@volcacius , i have just added a license. Apologies for the big delay.

**Comment by volcacius** [comment]
Thanks a mil!
